### PR TITLE
Pass along props

### PR DESCRIPTION
**Pull request by MartijnHols**
Hey,

We started using your library today. It's exactly what I've been looking for for a long time! Thanks 😄 

We made some changes we either need or want for [our project](https://github.com/WoWAnalyzer/WoWAnalyzer). We're using a fork now so there's both no haste nor any need to have these changes merged in, but hopefully it will help.

For this first PR I'd like to propose passing along all properties. In combination with the pre-existing `tagName` prop, this makes it possible to do things like:

```jsx
<Tooltip content="Search with Google" tagName="a" href="https://google.com">Search</Tooltip>
```

### CODE REVIEW

**Comment by bsidelinger912** [comment]
@MartijnHols some other folks are needing to pass along other native element props, so this is definitely something we want to do.  I'm a little wary of spreading anything that folks pass in though, for use with typescript I can extend React's html attribute type, I think I may try and limit to the properties in that type for non-typescript usage as well.  I'll think about about the best strategy for some kind of locking down of the props, but also allowing for a decent amount of flexibility.  I'm glad the component is working for you guys, and I really appreciate you contributing back!  I'll keep you posted on this and the other great ideas you've proposed for sure.

**Comment by bsidelinger912** [comment]
@MartijnHols I've been thinking more about this and I thinking of not doing it.  The reason is because the outer element is really just there to catch mouse and keyboard events, not really to be a functional element.  I added tagName and className in order to get around layout issues, but upon further consideration, I'm hesitant to go further down that rabbit hole.  The reason is you can put anything inside the tooltip as the "target", not just a string but any element.  Really if fragments supported events (which apparently they will some day), I'd remove the element altogether and let you just put your JSX in there as needed, to style and add attributes as needed.  I understand that not supporting this requires an extra element to be added to the DOM (for now) because there's the element that wraps everything and catches the events, then your inner element with with the href or whatever, but it'll be easier to switch to using fragments to catch events instead of elements.  For your example you can just do this: 
```
<Tooltip tagName="span" content="Search with Google">
    <a href="https://google.com">Search</a>
</Tooltip>
```
Other than adding an extra <span> to the DOM, I don't see an issue with this, do you?  In the future, with a fragment that extra span could go away.  I feel like if folks get in the habit of using <Tooltip> as an indirect way to add their element to the React tree, issues could arise and it would overload the intent of the component which is simply to handle tooltip related things.  This is just where I stand today, happy to keep this discussion going.

**Comment by MartijnHols** [comment]
I try hard to avoid adding extra unnecessary elements. This is for
- performance reasons (render delays is often death by a thousand cuts)
- cleanliness
- not everything can be nested (the best examples I can think of right now are `<table>` and `<svg>`, so maybe this isn't a big deal anymore)
- and I also don't want my CSS selectors to need extra levels of nesting as that makes it much more entwined with the markup (in other words I want my navigation to be `ul > li > a` if possible). Even worse would be if one element has a tooltip and another doesn't, then we need 2 selectors or a new class name for the same thing.

I'm fine with closing this PR if that's going to be your approach. Our fork has moved [quite far](https://github.com/bsidelinger912/react-tooltip-lite/compare/master...WoWAnalyzer:master) in a different direction where we got rid of the wrapper element entirely. We've already rewritten all our code to use this version and I think it's very convenient. We're ok with having to use the fork indefinitely and having to maintain that ourselves (if at all necessary).

I'll close this issue seeing as it goes against your vision. Thanks a lot for your work and this fine library!

**Comment by bsidelinger912** [comment]
Interestingly enough your fork now really seems to be achieving a similar goal to what I wanted from Fragments with events, which is not adding a wrapper element to the DOM.  I looked at how you did it and it's a cool idea, to just add the events to the element they pass.  At a glance, the practical difference between what you did and using a Fragment as the wrapper is really an implementation detail and wouldn't impact usage or results.  I may try something similar and swap out for an event handling fragment in the future (assuming that does happen, which may be up in the air).

**Pull request closed without merging**
