### PR TITLE
Upgrade react-minimalist-portal to support SSR

### PR DESCRIPTION
**Pull request by andrefgneves**
Hi. `react-minimalist-portal` was recently updated to [support SSR](https://github.com/pradel/react-minimalist-portal/releases/tag/v2.2.0). This PR updates its version.

### CODE REVIEW

**Comment by bsidelinger912** [comment]
@andrefgneves can you upgrade this with yarn, so yarn.lock gets updated too?  If you don't have yarn, and don't want to install it, I can do that too.

**Comment by andrefgneves** [comment]
Oh, yeah sure. Sorry, didn't notice the lock file.

**Comment by andrefgneves** [comment]
Done.

**Comment by bsidelinger912** [comment]
awesome thanks, I'll merge and publish this after work today.

**Comment by andrefgneves** [comment]
Great. Thank you.

**Comment by andrefgneves** [comment]
Hi. Do you think you'll be able to merge this soon?

**Comment by bsidelinger912** [comment]
Hey @andrefgneves sorry for the delay, this is published as v1.4.2.

**Comment by andrefgneves** [comment]
Awesome, thank you.

**Pull request merged**
