### PR TITLE
Add unhover controls to tooltip

### PR DESCRIPTION
**Pull request by simonas88**
I added a prop to control the tooltip dismissal delay on endHover event.

### CODE REVIEW

**Comment by bsidelinger912** [comment]
Hey @simonas88 thanks for the PR, I'll take a closer look this weekend, but at a glance this seems like a nice feature to have.

**Comment by simonas88** [comment]
@bsidelinger912 Have you had the chance to check the PR yet?

**Comment by bsidelinger912** [comment]
Hey @simonas88, the delay on this is because I need some time to sit down and test it, since there's no tests, or setup for manual testing in storybook or the example.  So I need to make additions to do manual, and in this case automated, testing  (I actually figured out how a testing strategy for this library a few months ago).  I'll try and write a contribution guide that explains how to test various facets so that it's clear what needs to happen to give me confidence things are tested sufficiently.  For now I have to either copy the feature into a new branch where I can test, or merge optimistically and add the necessary infrastructure to master in a followup commit before publishing.

**Comment by bsidelinger912** [comment]
Also worth noting for anyone looking at this that the types weren't updated, so this feature would not be available to typescript consumers (more reasons for me to write a contribution guide).

**Comment by bsidelinger912** [comment]
This is now released in v1.10.0.  The prop has been renamed to "mouseOutDelay" and it now works even if you don's specify tipContentHover=true, previously it only worked when that prop was set to true.  You can see this commit: https://github.com/bsidelinger912/react-tooltip-lite/commit/2a154293fe4014eac1439255c95dbf97c62fd0bb, to see the tests added, the usage in storybook for manual confirmation and the update to make it work without tipContentHover.

**Pull request merged**
